# Generated by Django 5.0.1 on 2024-01-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DevTools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('thumbnail', models.ImageField(blank=True, upload_to='ideas/%Y/%m/%d', verbose_name='Image')),
                ('content', models.TextField()),
                ('interst', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevTools.devtool')),
            ],
        ),
    ]
