# Generated by Django 5.0.1 on 2024-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('공포', '공포'), ('스릴러', '스릴러'), ('코믹', '코믹'), ('드라마', '드라마')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('running_time', models.IntegerField()),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=100)),
            ],
        ),
    ]
